export default {  
    greeting: 'français',
    'username':"Nom d'utilisateur",
    'password':'Mots de passe',
    'login':'CONNECTION',
    'use e-learning':'Utilisez votre identifiant Forma2 + elearning pour commencer',
    'Remember me':'se souvenir de moi',
    "Anglais":"Anglais",
    "Francais":"Français",
    "Espagnol":"Espagnol",
    "language":"langue",
    // home
    'Welcome back':'Bienvenue',
    'your':'Vos',
    'home':'ACCUEIL',
    'stats':'STATISTIQUES',
    'select':'Selectionnnez',
    'your task':'votre tache',
    'text expressions':'expressions en texte',
    'pictures and videos':'photos et vidéos',
    'new record':'ENREGISTREMENT',
    'Add new expression':'Nouvelle expression',
    'Add new audio':'Nouveau audio',
    'Record video and picture':'Vidéo et image',
    'All expressions':'Toutes les expressions',
    'View categories':'Voir les catégories',
    'Your recordings':'Vos enregistrements vidéos',
    'List of':'La liste de',
    'your expressions':'vos expressions',
    'Filter':'Filtrer',
    'by keyword':'par mot clé',
    'Type your one or two words':'tapez un ou deux mots',
    'by date':'par date',
    'Search':'Rechercher',
    'categories':'catégories',
    'See all':'Voir touts',
    'Nom du fichier:':'Nom du fichier:',
    'Date de création:':'Date de création:',
    'Description:':'Description:',
    'Image transcription:':"Transcription de l'image",
    "search for expressions":"Recherche d'expression",
    'Translated:':'Traduction',
    'Other language':'Autre langue',
    'close':'Fermer',
    'Record':'Enregistrement',
    "Your recording language":"Votre langue d'enregistrement",
    "Category optional":"Catégorie (Facultatif)",
    'Add New':'Nouveau',
    'Enter your new category name':'Entrez votre nouveau nom de catégorie',
    'Add':'Ajouter',
    'record audio':'ENREGISTREMENT AUDIO',
    'REAL-TIME TRANSCRIPTION':'TRANSCRIPTION',
    'CANCEL':'ANNULER',
    "this week":"cette semaine",
     "this month":"ce mois-ci",
     "this year":"cette année",
     "ALL EXPRESSIONSs":"TOUTES LES EXPRESSIONS",
     "IMAGES DETAILS":"DÉTAILS DES IMAGES",


    // video and picture

    "video and picture":"vidéo et photo",
    "RECORD":"ENREGISTER",
    "Uploading":"Téléchargement",
    "GET RECORDED FILE":"OBTENIR UN FICHIER ENREGISTRÉ",
    "Edit":"Modifier",
    "text":"le texte",
    "your text":"votre texte",
    "Translated text":"Texte traduit",
    "SAVE":"ENREGISTRER",

//  add new expression
    "new expression":"Nouvelle expression",
    "Enter your new term":"Entrez votre nouveau terme",
    "Enter your translated term":"Entrez votre terme traduit",
    "Target language":"Langue cible",
    "CONFIRM":"CONFIRMER",
    "DELETING EXPRESSION":"SUPPRESSION D'EXPRESSION",
    "Are you sure you want to delete this Expression":"Êtes-vous sûr de vouloir supprimer cette expression ?",

    //Jitsi
    "Get Jitsi":"Obtenir Jitsi",
    "Open Jitsi":"Ouvrir Jitsi",

    // newpic
    "French":"Français",
    "Describe":"Décrire",
    // sendpic
    "Description text":"Texte de descriptif",
    "DELETING CATEGORY":"SUPPRESSION DE CATEGORIE",
    "Are you sure you want to delete this Category?":"Êtes-vous sûr de vouloir supprimer cette catégorie ?",
    "NO":"NON",
    "YES":"OUI",
    "ALL CATEGORIES":"TOUTES LES CATÉGORIES",
    "Search for categories":"Rechercher des catégories ...",
    "Category":"la catégorie",
    "Cat":"Categorie",
    "Description":"Description",
    "Describe your category":"Décrivez votre catégorie",

// RECORDINGS
"RECORDINGS":"ENREGISTREMENT",
"video":"vidéos",
"DELETING VIDEO":"SUPPRESSION VIDEO",
"Are you sure you want to delete this video":"Voulez-vous vraiment supprimer cette vidéo ?",

// RECORDE AUDIO
"RECORDE AUDIO":"ENREGISTREMENT AUDIO",
"What do you whant with this audio File":"Que voulez-vous avec ce fichier audio",
"Get transcription":"Obtenir la transcription",
"Tanscript and save":"Transcrire et sauvegarder",
"Your speech":"Votre discours",
"translate to":"traduire en",
"Uploading and transcripting":"Téléchargement et transcription",

// speech to text
"Yoursp":"Votre",
"Speech":"Discours",
"Clic the mic to Start/End":"Cliquez sur le micro pour démarrer/fin",
"DELETING EXPRESSION":"DELETING EXPRESSION",
"Are you sure you want to delete this expression":"Are you sure you want to delete this expression?",

  };